project:
  type: website
website:
  site-url: "https://xiang-li-fin.github.io"
  title: ""
  favicon: logo.jpg
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research/research.qmd
      - text: CV
        href: files/CV_Xiang_Li.pdf 
        target: _blank
#      - text: Blog
#        href: posts/index.qmd
  google-analytics: ""
  # cookie-consent: true
  open-graph: true
  search: false
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto
