project:
  type: website
website:
  site-url: "https://xiang-li.com"
  title: ""
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research/index.qmd
      - text: CV
        href: CV_Xiang_Li_2025Nov23.pdf 
#      - text: Blog
#        href: posts/index.qmd
  favicon: favicon.ico
  google-analytics: ""
  # cookie-consent: true
  open-graph: true
  search: false
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto
